# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-10-18 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'scheduledTask',
                'permissions': (('view_scheduledTask', '\u67e5\u770b\u5b9a\u65f6\u4efb\u52a1'), ('edit', '\u4fee\u6539\u5b9a\u65f6\u4efb\u52a1')),
            },
        ),
    ]
