# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-10-18 17:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduled_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduledtask',
            options={'permissions': (('view_scheduledTask', '\u67e5\u770b\u5b9a\u65f6\u4efb\u52a1'), ('edit_scheduledTask', '\u4fee\u6539\u5b9a\u65f6\u4efb\u52a1'))},
        ),
    ]
