# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-10-18 17:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduled_tasks', '0002_auto_20171018_1723'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScheduledTask',
        ),
    ]
