# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-10-18 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduled_tasks', '0003_delete_scheduledtask'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'scheduledTask',
                'permissions': (('viewTask', '\u67e5\u770b\u5b9a\u65f6\u4efb\u52a1'), ('editTask', '\u4fee\u6539\u5b9a\u65f6\u4efb\u52a1')),
            },
        ),
    ]
