# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-11-01 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduled_tasks', '0004_scheduledtask'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u540d\u79f0')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u63cf\u8ff0')),
                ('host', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u4e3b\u673a')),
                ('user', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u7528\u6237')),
                ('passwd', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5bc6\u7801')),
                ('db', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u6570\u636e\u5e93\u5b9e\u4f8b')),
                ('type', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u6570\u636e\u5e93\u7c7b\u578b')),
            ],
            options={
                'db_table': 'database',
            },
        ),
    ]
