# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-11-01 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduled_tasks', '0006_auto_20171101_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseinfo',
            name='host',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='\u4e3b\u673a'),
        ),
        migrations.AlterField(
            model_name='databaseinfo',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='\u540d\u79f0'),
        ),
    ]
